version: "3"
services:
  db:
    container_name: ScraperDB
    image: mysql:8
    ports:
      - "6000:3306"
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ScraperDBVol:/var/lib/mysql
volumes:
  ScraperDBVol: